### ISSUE TITLE
Retry button is not clickable

### ISSUE THREAD

**Issue by taneltm** [KarthikNedunchezhiyan/google-chrome-dino#1]
The retry button is clickable in the original game.
![image](https://user-images.githubusercontent.com/5690464/130420858-d79e72dc-2a7a-4fa8-af41-75e1db17da6a.png)

**Comment by KarthikNedunchezhiyan** [comment]
@taneltm thanks for the report. This is indeed a bug. I have made a fix and published it. Will close this issue once you confirmed that the issue has been fixed.

**Comment by taneltm** [comment]
Confirmed, it's now fixed.
